/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rule#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rule#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rule#getThenPart <em>Then Part</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rule#getExample <em>Example</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rule#getLayer <em>Layer</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Seq)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRule_Condition()
   * @model containment="true"
   * @generated
   */
  Seq getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Rule#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Seq value);

  /**
   * Returns the value of the '<em><b>Then Part</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then Part</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Part</em>' containment reference.
   * @see #setThenPart(TransferModel)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRule_ThenPart()
   * @model containment="true"
   * @generated
   */
  TransferModel getThenPart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Rule#getThenPart <em>Then Part</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Part</em>' containment reference.
   * @see #getThenPart()
   * @generated
   */
  void setThenPart(TransferModel value);

  /**
   * Returns the value of the '<em><b>Example</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Example</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Example</em>' attribute.
   * @see #setExample(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRule_Example()
   * @model
   * @generated
   */
  String getExample();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Rule#getExample <em>Example</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Example</em>' attribute.
   * @see #getExample()
   * @generated
   */
  void setExample(String value);

  /**
   * Returns the value of the '<em><b>Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Layer</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layer</em>' reference.
   * @see #setLayer(Layer)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRule_Layer()
   * @model
   * @generated
   */
  Layer getLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Rule#getLayer <em>Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Layer</em>' reference.
   * @see #getLayer()
   * @generated
   */
  void setLayer(Layer value);

} // Rule
