/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transfer Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TransferModel#getSeq <em>Seq</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTransferModel()
 * @model
 * @generated
 */
public interface TransferModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Seq</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Call}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Seq</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seq</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTransferModel_Seq()
   * @model containment="true"
   * @generated
   */
  EList<Call> getSeq();

} // TransferModel
